REPORT ZR001.





SELECTION-SCREEN: BEGIN OF BLOCK b0 WITH FRAME TITLE text-001.

SELECTION-SCREEN SKIP.


SELECTION-SCREEN BEGIN OF LINE.

PARAMETER p_rad1 RADIOBUTTON GROUP gr1.
SELECTION-SCREEN COMMENT 3(20) text-002.

PARAMETER p_rad2 RADIOBUTTON GROUP gr1. 
SELECTION-SCREEN COMMENT 27(10) text-003.

SELECTION-SCREEN END OF LINE.


SELECTION-SCREEN SKIP.
PARAMETERS p_param type tabela-campo.


SELECTION-SCREEN: END OF BLOCK b0.



SELECTION-SCREEN: BEGIN OF BLOCK b1 WITH FRAME TITLE text-004.

PARAMETER p_rad3 RADIOBUTTON GROUP gr2.
PARAMETER p_rad4 RADIOBUTTON GROUP gr2. 

PARAMETERS: p_param2 type tabela-campo.


SELECTION-SCREEN: END OF BLOCK b1.


SELECTION-SCREEN: BEGIN OF BLOCK b2 WITH FRAME. "TITLE text-000

PARAMETER p_rad3 RADIOBUTTON GROUP gr2.
PARAMETER p_rad4 RADIOBUTTON GROUP gr2. 

PARAMETERS: p_param2 type tabela-campo.


SELECTION-SCREEN: END OF BLOCK b2.


SELECTION-SCREEN: BEGIN OF BLOCK b3. "WITH FRAME. "TITLE text-000

PARAMETER p_rad3 RADIOBUTTON GROUP gr2.
PARAMETER p_rad4 RADIOBUTTON GROUP gr2. 

PARAMETERS: p_param2 type tabela-campo.


SELECTION-SCREEN: END OF BLOCK b3.

"SELECTION-SCREEN: BEGIN OF BLOCK b3. "WITH FRAME. "TITLE text-000

PARAMETER p_rad3 RADIOBUTTON GROUP gr2.
PARAMETER p_rad4 RADIOBUTTON GROUP gr2. 

PARAMETERS: p_param2 type tabela-campo.


"SELECTION-SCREEN: END OF BLOCK b3.

TABLES: TABELA. "utilizado quando temos um select-options com tipo de referencia para tabela

SELECT-OPTIONS so_campo1 for tabela-campo1. 
SELECT-OPTIONS so_campo2 for tabela-campo2 NO INTERVALS. 
SELECT-OPTIONS so_campo2 for tabela-campo2 NO EXTENSION.
SELECT-OPTIONS so_campo2 for tabela-campo2 NO EXTENSION NO INTERVALS.
 